# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Voices of Gay Rodeo
email: rscofield@uidaho.edu
description: Oral Histories from the International Gay Rodeo Association
date: 2019

# library's domain (only changed if using github pages)
url: https://www.voicesofgayrodeo.com # https://uidaholib.github.io 
baseurl: # /gayrodeo_source
github_username: uidaholib
github_repository: https://github.com/uidaholib/gayrodeo_source
# Collection's objects dir location
objects: /images/team

collections:
  transcripts:
      output: true
      permalink: /interviews/:collection/:name
  interviews:
      output: true
      permalink: /:collection/:name

defaults:
  - scope:
      type: transcripts
    values:
      layout: transcript
  - scope:
      type: interviews
    values:
      layout: interviews
      


# Build settings
markdown: kramdown
